cors:
  originPatterns: http://localhost:8080,http://localhost:5050
spring:
  application:
    name: cloudkeeper
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudkeeper?useTimezone=true&serverTimezone=UTC
    username: developer
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
